### ISSUE TITLE
demo does not work well

### ISSUE THREAD

**Issue by heroacool** [wh200720041/iscloam#9] opened 2020-07-23 06:30 UTC
![image](https://user-images.githubusercontent.com/5468049/88257373-1ed95b80-ccf0-11ea-8322-11266c23053f.png)

Run the cmd
roslaunch iscloam iscloam_mapping.launch

In the launch file, I use the default  kitti data: 2011_09_30_0018.bag.
The picture shows the result. The pose estimation seems to be divergent.

The log info: "map errornot enough points in map to associate"
Could you  help me?

**Comment by wh200720041** [comment] 2020-07-23 13:53
Hi @heroacool 

Thanks for testing this project. 

The algorithm is correct. This problem shouldn't occurs, but based on some feedback, it happens in some computer. I doubt this is caused by different versions of PCL. However, I couldn't reproduce this bug in my platform and I am not sure about this issue. 

I would recommend to change to another pc for a quick test. It should work for most of PCs.

This problem was also reported by other user. you may find the question from below link.
[https://github.com/wh200720041/floam/issues/5](url)

Based on his feedback, he solved the problem by changing pc.

Let me know if that works

Han

**Comment by wh200720041** [comment] 2020-07-31 05:58
Hi if there is no questions I shall close this issue, thanks

**Closed by wh200720041** 2020-07-31 05:58 UTC
